### ISSUE TITLE
An unexpected error happened when open velaux

### ISSUE THREAD

**Issue by regend** [kubevela/velaux#823]
**Describe the bug**
when i open velaux in version v1.8.1,the brower shows these messages:
An unexpected error happened
详情TypeError: Cannot convert undefined or null to object

    at g2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:208200)
    at tr
    at g2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:204122)
    at tbody
    at g2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:211066)
    at table
    at g2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:227247)
    at div
    at g2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:229388)
    at S2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:251738)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:274261)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:255676)
    at S2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:260866)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:268051)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:246255)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:296003)
    at x2 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:298579)
    at Ht (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:1:61320)
    at div
    at Jn (http://localhost:30000/public/build/7504.1c50aa8a9e082812de1a.js:7:41818)
    at Jt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:72162)
    at B (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:6:2275)
    at Ht (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:1:61320)
    at div
    at Xn (http://localhost:30000/public/build/7504.1c50aa8a9e082812de1a.js:7:52081)
    at Jt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:72162)
    at wt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:87485)
    at wt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:99497)
    at lf
    at div
    at div
    at div
    at Nf (http://localhost:30000/public/build/7504.1c50aa8a9e082812de1a.js:115:161564)
    at _1 (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:1:65666)
    at xf (http://localhost:30000/public/build/7504.1c50aa8a9e082812de1a.js:115:162472)
    at component
    at wt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:87485)
    at jf (http://localhost:30000/public/build/7504.1c50aa8a9e082812de1a.js:115:170667)
    at wt (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:99497)
    at F (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:105336)
    at ft (http://localhost:30000/public/build/4794.03caa2c92dc8662e4a29.js:72:68429)
    at X

**To Reproduce**

**Screenshots**
![velaux-error](https://github.com/kubevela/velaux/assets/5510284/c751b470-5434-4f04-9e5e-c4523b17a92e)

**KubeVela Version**

1.8.1

**Additional context**
i can't find any error logs in both velaux or vela-core

**Comment by achauve** [comment]
Same with 1.8.2 . Happens only after a while of using the ux.

**Comment by lxkaka** [comment]
same with 1.8.2， when create a new application. 
This is a serious issue that causes the application to be completely unusable.
